SELECT
MODEL_TYPE
, SUM(CAST(STOCK AS INT)) AS STOCK_AMOUNT
, SUM(CAST(STOCK AS INT) * CAST(PRICE AS FLOAT64) AS STOCK_VALUE
FROM `data-analytics-bootcamp-363212.course14.circle_stock_clean`
GROUP BY MODEL_TYPE
ORDER BY STOCK, COLOUR
